### ISSUE TITLE
.Xdefaults

### ISSUE THREAD

**Issue by Ithalos** [davosken/dotfiles#1]
Isn't .Xdefaults deprecated? I think .Xresources is the new version.

See: https://wiki.archlinux.org/index.php/X_resources#Load_resource_file

**Comment by davosken** [comment]
Hm, didn't know that there was an actual difference to these 2 files. Now my solution is I will keep my .Xdefaults but I will modify .xinitrc to xrdb .Xdefaults. So it will function completely the same as a .Xresources file. Will be added in next push.
